#!/usr/bin/env bash
set -euo pipefail
# Run only after uploading the archive and manifest generated by package-preview.cjs.
site=/var/www/casanova-studio
previous=$(readlink -f "$site/current")
release="$site/releases/20261004-phaser-preview"
test "$previous" = "$site/releases/20261001-direct"
test ! -e "$release"
test -f /tmp/success-preview.tar.gz
test -f /tmp/success-preview.sha256
test -f /tmp/success-migration-original.sha256
test -f /tmp/success-migration-sites-before.sha256
# Existing files are linked and never edited. This avoids another full artwork copy.
cp -al "$previous" "$release"
mkdir "$release/the-secret-of-my-success/migration"
mkdir "$release/the-secret-of-my-success/migration/assets"
cp -al "$previous/the-secret-of-my-success/assets/." "$release/the-secret-of-my-success/migration/assets/"
tar -xzf /tmp/success-preview.tar.gz -C "$release/the-secret-of-my-success/migration"
(cd "$release/the-secret-of-my-success/migration" && sha256sum -c /tmp/success-preview.sha256)
(cd "$release" && sha256sum -c /tmp/success-migration-original.sha256 > /tmp/success-preview-original-check.txt)
sha256sum -c /tmp/success-migration-sites-before.sha256
ln -s "$release" "$site/current-preview-next"
mv -Tf "$site/current-preview-next" "$site/current"
printf 'Preview release: %s\nRollback: ln -s %s %s/current-rollback && mv -Tf %s/current-rollback %s/current\n' "$release" "$previous" "$site" "$site" "$site"
rm /tmp/success-preview.tar.gz
